name: 构建并推送 Docker 镜像

于:
  push:
    branches:
      - main

环境:
  注册表: ghcr.io
 IMAGE_NAME: ${{ github.repository }}

作业:
 构建:
    运行操作系统: ubuntu-latest
    权限:
      文件内容: 读取
      软件包: 写入
    步骤:
      - 名称: 检出代码
        uses: actions/checkout@v4

      - name: 设置镜像名称为小写
        run: echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >> $GITHUB_ENV
        env:
          IMAGE_NAME: ${{ github.repository }}

      - name: 设置 Docker Buildx
        使用: docker/setup-buildx-action@v3

      - name: 登录 GitHub 容器注册表
        使用: docker/login-action@v3
        with:
          注册表: ${{ env.REGISTRY }}
          用户名: ${{ github.actor }}
          密码: ${{ secrets.GHCR_TOKEN }}

      - 名称: 构建并推送 Docker 镜像
        使用: docker/build-push-action@v5
        with:
          context: .
          push: true
标签: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:latest
